/*
 MIT License <http://www.opensource.org/licenses/mit-license.php>
*/
var d=true,e=null,n=false;function o(){return function(){}}function s(a){return function(b){this[a]=b}}function z(a){return function(){return this[a]}}if(typeof A=="undefined")var A={};if(typeof A.aa=="undefined")A.aa={};if(typeof A.pa=="undefined")A.pa={};
A.aa.Vc=function(){A.aa.object.call(this);A.pa["jspd.objects.js"]=A.aa.Vc;this.label="js";this.ba=[new A.da(this),new A.da(this),new A.da(this),new A.da(this),new A.da(this)];this.ca=[new A.fa(this),new A.fa(this),new A.fa(this),new A.fa(this),new A.fa(this)];this.code="";this.execute=function(){B&&console.log("execute@jspd.objects.inout");var a=this.ba[0].value;this.code!=""&&eval(this.code);a!=e&&this.ca[0].send(e)};this.Zb=function(){var a=document.createElement("div");a.setAttribute("style","font-size:20px;padding:10px;");
a.appendChild(document.createTextNode("Javascript code"));a.appendChild(document.createElement("br"));var b=document.createElement("textarea");b.setAttribute("class","js");b.appendChild(document.createTextNode(this.code));a.appendChild(b);var c=new C(a,this.ga.db),f=this;a=[];a.push(["<<",function(){c.close()}]);a.push(["Save",function(){f.code=b.value;c.close()}]);c.toolbar=new A.view.toolbar(a);c.open()}};
A.aa.Rc=function(){A.aa.object.call(this);A.pa["jspd.objects.inout"]=A.aa.Rc;this.label="inout";this.ba=[new A.da(this),new A.da(this),new A.da(this),new A.da(this)];this.ca=[new A.fa(this),new A.fa(this),new A.fa(this),new A.fa(this)];this.execute=function(){B&&console.log("execute@jspd.objects.inout");this.ca[0].send(this.ba[0].value)}};
A.aa.print=function(){A.aa.object.call(this);A.pa["jspd.objects.print"]=A.aa.print;this.label="print";this.ba=Array(new A.da(this));this.ca=[];this.execute=function(){var a="";for(param in this.Ba)a+=this.Ba[param]+" ";a+=this.ba[0].value;B?console.log("execut@jspd.objects.print",a):console.log(a)}};
A.aa.xa=function(){A.aa.object.call(this);A.pa["jspd.objects.xhr"]=A.aa.xa;this.label="xhr";this.ba=[new A.da(this),new A.da(this),new A.da(this)];this.ca=Array(new A.fa(this));this.xa=e;this.Ga=function(){if(window.XMLHttpRequest)this.xa=new XMLHttpRequest;else if(window.od)try{this.xa=new ActiveXObject("Msxml2.XMLHTTP")}catch(a){this.xa=new ActiveXObject("Microsoft.XMLHTTP")}};this.execute=function(){if(this.xa!=e){var a=this;this.xa.onreadystatechange=function(){a.xa.readyState==4&&a.xa.status==
200&&a.ca[0].send(a.xa.responseText)};this.xa.open("GET","xhr.html",d);this.xa.send(e)}};this.Nb=function(){this.xa=e}};
A.aa.Yc=function(){A.aa.object.call(this);A.pa["jspd.objects.metro"]=A.aa.Yc;this.label="metro";this.ba=Array(new A.da(this));this.ca=Array(new A.fa(this));this.timeout=this.Da=this.mb=e;this.execute=function(){if(this.ba[0].value==1){this.mb=1;if(this.Da==e){this.ca[0].send(1);this.Wa()}}else{this.mb=0;clearInterval(this.Da);this.Da=e}};this.Wa=function(){if(this.Da!=e){clearInterval(this.Da);this.Da=e}this.mb&&this.setInterval(this.Fa(1))};this.Mb=function(){this.mb&&this.timeout!=this.Fa(1)&&this.setInterval(this.Fa(1))};
this.setInterval=function(a){this.Da!=e&&clearInterval(this.Da);var b=this;this.Da=setInterval(function(){b.ca[0].send(1)},a);this.timeout=a};this.yb=function(){this.Da=e}};A.aa.wc=function(){A.aa.object.call(this);A.pa["jspd.objects.bang"]=A.aa.wc;this.label="bang";this.ba=Array(new A.da(this));this.ca=Array(new A.fa(this));this.Pa=function(){B&&console.log("event@jspd.objects.bang");this.ca[0].send(1)};this.execute=function(){this.ca[0].send(this.ba[0].value);B&&console.log("execut@jspd.objects.bang")}};
A.aa.add=function(){A.aa.object.call(this);A.pa["jspd.objects.add"]=A.aa.add;this.label="+";this.ba=[new A.da(this),new A.da(this)];this.ca=Array(new A.fa(this));this.na=e;this.execute=function(){if(this.ba[1].value!=e){B&&console.log("execute@jspd.objects.add",this.ba[1],"in1:"+this.ba[1].value);this.na=this.ba[1].value}else{var a=this.ba[0].value+this.na;this.na=e;this.ca[0].ports[0]!=e&&B&&console.log("execute@jspd.objects.add",a+"->"+this.ca[0].ports[0].object.label);this.ca[0].send(a)}}};
A.aa.Sc=function(){A.aa.object.call(this);A.pa["jspd.objects.int"]=A.aa.Sc;this.label="int";this.ba=[new A.da(this),new A.da(this)];this.ca=Array(new A.fa(this));this.na=e;this.execute=function(){B&&console.log("execute@jspd.objects.int","in0:"+this.ba[0].value,"in1:"+this.ba[1].value);if(this.ba[0].value!=e){this.na=this.ba[0].value;this.ca[0].send(this.na)}if(this.ba[1].value!=e)this.na=this.ba[1].value}};
A.aa.alert=function(){A.aa.object.call(this);A.pa["jspd.objects.alert"]=A.aa.alert;this.label="alert";this.ba=Array(new A.da(this));this.ca=[];this.execute=function(){alert(this.ba[0].value)}};
A.aa.Ac=function(){A.aa.object.call(this);A.pa["jspd.objects.counter"]=A.aa.Ac;this.label="counter";this.ba=[new A.da(this),new A.da(this)];this.ca=Array(new A.fa(this));this.min=1;this.max=10;this.na=1;this.execute=function(){if(this.ba[1].value!=e||this.na>=this.max+1)this.na=this.min;this.ba[0].value!=e&&this.ca[0].send(this.na++)};this.Mb=function(){if(this.Fa(1)!=e)this.max=parseInt(this.Fa(1));if(this.Fa(2)!=e)this.min=parseInt(this.Fa(2))}};
A.aa.join=function(){A.aa.object.call(this);A.pa["jspd.objects.join"]=A.aa.join;this.label="join";this.ba=[new A.da(this),new A.da(this)];this.ca=Array(new A.fa(this));this.na=e;this.execute=function(){if(this.ba[1].value!=e){this.na=this.ba[1].value;this.ba[1].value=e}this.ba[0].value!=e&&this.ca[0].send(this.ba[0].value+","+this.na)}};
A.aa.Wc=function(){A.aa.object.call(this);A.pa["jspd.objects.meter"]=A.aa.Wc;this.label="meter";this.ba=Array(new A.da(this));this.ca=Array(new A.fa(this));this.timeout=e;this.Ga=function(){this.la=new A.ia.La(24,24);this.la.add(new A.ia.nb(8,"#EEEEEE"),4,4)};this.execute=function(){B&&console.log("execut@jspd.objects.meter",this.ba[0].value);this.la.lc();this.ga.canvas.oa=d;this.ba[0].value?this.la.add(new A.ia.nb(8,"#00FF00"),4,4):this.la.add(new A.ia.nb(8,"#FF0000"),4,4);if(this.timeout==e){var a=
this;this.timeout=setTimeout(function(){a.la.add(new A.ia.nb(8,"#EEEEEE"),4,4);clearTimeout(a.timeout);a.timeout=e;a.ga.canvas.oa=d},50)}};this.Nb=o();this.yb=function(){if(this.ia==e)this.ia=[]}};
A.aa.button=function(){A.aa.object.call(this);A.pa["jspd.objects.button"]=A.aa.button;this.label="button";this.ba=Array(new A.da(this));this.ca=Array(new A.fa(this));this.na=n;this.ia=[];this.Ga=function(){this.la=new A.ia.La(24,24)};this.Pa=function(){this.na=!this.na;this.Wa();this.ca[0].send(this.na?d:n)};this.Wb=function(){this.la.add(new A.ia.Ua(16,16),4,4);this.la.add(new A.ia.Ua(16,-16),4,20)};this.Wa=function(){this.la.lc();this.na&&this.Wb();this.ga.canvas.oa=d};this.execute=function(){if(this.na!=
this.ba[0].value){this.na=this.ba[0].value;this.Wa()}this.ca[0].send(this.na?d:n)};this.yb=function(){if(this.na){alert("todo");this.Wb()}}};A.aa.message=function(){A.aa.object.call(this);A.pa["jspd.objects.message"]=A.aa.message;this.label="message";this.ba=Array(new A.da(this));this.ca=Array(new A.fa(this));this.Ga=o();this.execute=function(){this.la.zb(this.ba[0].value);this.ga.canvas.oa=d};this.Pa=function(){this.ca[0].send(this.Fa(1))}};
A.aa.Ca=function(){A.aa.object.call(this);A.pa["jspd.objects.table"]=A.aa.Ca;this.label="table";this.ba=Array(new A.da(this));this.ca=[];this.Xa=[];this.Ga=function(){this.la=new A.ia.La(150,100)};this.execute=function(){this.Xa.length>150&&this.Xa.shift();if(this.ba[0].value!=e){var a=this.ba[0].value.split(",");a=[parseInt(a[0]),parseInt(a[1])];this.Xa.push(a);var b=this.ga.canvas.getContext().createImageData(150,100);for(a in this.Xa){var c=(parseInt(this.Xa[a][0])+parseInt(this.Xa[a][1])*100)*
4;b.data[c+0]=40;b.data[c+1]=40;b.data[c+2]=40;b.data[c+3]=255}this.ga.canvas.getContext().putImageData(b,this.ja,this.ka)}}};A.aa.sin=function(){A.aa.object.call(this);A.pa["jspd.objects.sin"]=A.aa.sin;this.label="sin";this.ba=Array(new A.da(this));this.ca=Array(new A.fa(this));this.execute=function(){this.ca[0].send(Math.sin(this.ba[0].value))}};remove=function(a,b){if(b>0){var c=a.splice(0,b);for(a.shift();c.length>0;)a.unshift(c.pop())}else a.shift()};var B=0;function D(){}
function E(a){if(a.touches!=e&&a.touches.length){a.qa=a.changedTouches[0].pageX;a.ra=a.changedTouches[0].pageY}else if(a.layerX||a.layerX==0){a.qa=a.layerX;a.ra=a.layerY}else if(a.offsetX||ev.offsetX==0){a.qa=a.offsetX;a.ra=a.offsetY}a.qa+=0.5;a.ra+=0.5;return a}function F(a,b){if(a!=e&&a.ua!=e)return a.ua;return G(a)==b}
function G(a){if(typeof a=="object"){if(a===e)return"null";if(a.constructor==[].constructor)return"array";if(a.constructor==(new Date).constructor)return"date";if(a.constructor==RegExp().constructor)return"regex";if(a.constructor==(new A.da).constructor)return"inlet";if(a.constructor==(new A.fa).constructor)return"outlet";return"object"}return typeof a}function H(a){a=window.event||a;return a=a.charCode||a.keyCode}
function I(a){if(a!=e){if(typeof a.toSource!=="undefined"&&typeof a.callee==="undefined")return a.toSource();switch(typeof a){case "number":case "boolean":case "function":return a;case "string":return"'"+a+"'";case "object":var b;if(a.constructor===Array||typeof a.callee!=="undefined"){if(a.length>0){b="[";var c,f=a.length;for(c=0;c<f-1;c++)b+=I(a[c])+",";b+=I(a[c])+"]"}}else{b="{";for(c in a)b+=c+":"+I(a[c])+",";b=b.replace(/\,$/,"")+"}"}return b;default:return"UNKNOWN"}}}
if(typeof A=="undefined")A={};
A.controller=function(){this.qd=this.Lb=this.object=this.db=e;this.aa=[];this.ea=[];this.ub=this.tb=this.canvas=e;this.Jb=n;this.ta=[];this.vb=n;this.kc=this.jb=this.ib=e;this.add=function(a,b,c){B&&console.log("add@jspd.controller",a);a.ja=b;a.ka=c;a.width=100;a.height=20;b=this.canvas.add(a.Nc(),b,c);this.canvas.oa=d;a.ya=b;this.aa.push(a)};this.ed=function(){for(object in this.ta)this.remove(this.ta[object])};this.remove=function(a){if(a.ua=="connection")for(i=0;i<this.ea.length;i++)if(this.ea[i]!=
e)if(this.ea[i]===a){B&&console.log("remove@jspd.controller","rm connection",this.ea[i].ya);this.canvas.remove(this.ea[i].ya);this.canvas.oa=d;this.ea[i].remove();this.ea[i]=e}if(a.ua=="jspd.objects.object")for(i=0;i<this.aa.length;i++)if(this.aa[i]!=e)if(this.aa[i]===a){B&&console.log("remove@jspd.controller","rm object",this.aa[i].label);this.canvas.remove(this.aa[i].ya);this.canvas.oa=d;this.aa[i].remove();this.aa[i]=e}};this.empty=function(){for(obj in this.aa)this.aa[obj]!=e&&this.remove(this.aa[obj]);
this.aa=[];B&&console.log("empty@jspd.controller","before",this.ea);for(obj in this.ea){B&&console.log("empty@jspd.controller","remove conn",this.ea[obj]);this.ea[obj]!=e&&this.remove(this.ea[obj])}B&&console.log("empty@jspd.controller","after",this.ea);this.ea=[];B&&console.log("empty@jspd.controller","rest",this.aa)};this.Tc=function(a){switch(a){case "iphone":if(navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPod/i))return d;return n;default:return n}};this.run=function(){this.db=
document.getElementById("jspd");this.canvas=new A.ia.canvas(document.getElementById("imageView"));this.canvas.Ib();var a=this;this.canvas.ma.addEventListener("mousedown",function(k){k.preventDefault();a.Pa(k)},n);this.canvas.ma.addEventListener("touchstart",function(k){k.preventDefault();a.Pa(k)},n);this.canvas.ma.addEventListener("mouseup",function(k){k.preventDefault();a.kb(k)},n);this.canvas.ma.addEventListener("touchend",function(k){k.preventDefault();a.kb(k)},n);this.canvas.ma.addEventListener("mousemove",
function(k){k.preventDefault();a.Qa(k)},n);this.canvas.ma.addEventListener("touchmove",function(k){k.preventDefault();a.Qa(k)},n);this.canvas.ma.addEventListener("keypress",function(k){a.Dd(k)},n);var b=document.getElementById("toolbar"),c=document.createElement("select");c.setAttribute("class","select");c.addEventListener("change",function(){a.ld(A.pa[this.value])},n);var f=document.createElement("option"),g=document.createTextNode("-----------");f.appendChild(g);c.appendChild(f);f=[];for(object in A.aa)object!=
"object"&&f.push(new A.aa[object]);for(object in A.pa)if(object!="object"){f=document.createElement("option");g=document.createTextNode(object);f.appendChild(g);c.appendChild(f)}b.appendChild(c);this.Fd=setInterval(function(){a.oa()},10);this.kc=new A.view.bd(this);this.kc.ad(A.Za.pb(this,this.load));this.ic()};this.oa=function(){this.canvas.cd()};this.ld=s("object");this.Hb=function(a,b){for(obj in this.aa)if(this.aa[obj]!=e)if(a>=this.aa[obj].ja&&a<=this.aa[obj].ja+this.aa[obj].la.width&&b>=this.aa[obj].ka&&
b<=this.aa[obj].ka+this.aa[obj].la.height)return this.aa[obj];return e};this.vd=function(a,b){for(connection in this.ea)if(this.ea[connection]!=e){var c=[];c.sx=this.ea[connection].fa.object.ja+this.ea[connection].fa.x+5;c.sy=this.ea[connection].fa.object.ka+this.ea[connection].fa.y+4;c.ex=this.ea[connection].da.object.ja+this.ea[connection].da.x+5;c.ey=this.ea[connection].da.object.ka+this.ea[connection].da.y;if(c.sx<=c.ex&&a>c.sx&&b>c.sy&&a<c.ex&&b<c.ey||c.sx>=c.ex&&a<c.sx&&b>c.sy&&a>c.ex&&b<c.ey)return this.ea[connection]}return e};
this.Qa=function(a){a=E(a);if(this.ta.length>0&&this.vb){for(object in this.ta)this.ta[object].Vb(a.qa+(this.ta[object].ja-this.ib),a.ra+(this.ta[object].ka-this.jb))&&this.ta[object].Ya(a.qa+(this.ta[object].ja-this.ib),a.ra+(this.ta[object].ka-this.jb));this.ib=a.qa;this.jb=a.ra;this.canvas.oa=d}if(this.Jb){this.canvas.Hc(this.tb,this.ub,a.qa-this.tb,a.ra-this.ub);this.canvas.oa=d;this.hd(this.tb,this.ub,a.qa,a.ra)}else{var b=this.Hb(a.qa,a.ra);if(b!=e){this.Lb=b;b.Qa(a)}else{this.Lb=e;this.canvas.ma.style.cursor=
"default"}}};this.kb=function(a){a=E(a);this.Jb=n;this.canvas.Na.clearRect(0,0,this.canvas.ma.width,this.canvas.ma.height);if(this.ta.length>0)if(this.vb){this.vb=n;this.jb=this.ib=e}else{var b=this;document.addEventListener("keypress",function(c){this.removeEventListener("keypress",arguments.callee,n);var f=H(c);if(f=="8"||f=="115")b.ed()},n)}};this.Pa=function(a){a=E(a);var b=e;b=this.Tc("iphone")?this.Hb(a.qa,a.ra):this.Lb;if(b!=e){var c=b.dc(a.qa,a.ra);if(F(c,"outlet")){this.rc();a=new A.zc(this);
a.kd(this.canvas);a.start(c)}else if(F(c,"inlet"))B&&console.log("onMouseDown@jspd.controller","no action for inlet");else{B&&console.log("onMouseDown@jspd.controller",b);if(b.selected){this.vb=d;this.ib=a.qa;this.jb=a.ra}else b.Pa(a)}}else{this.rc();if(this.object!=e){c=new this.object;c.oc(this);c.ja=a.qa;c.ka=a.ra;this.add(c,a.qa,a.ra);this.object=e}else{this.Jb=d;this.tb=a.qa;this.ub=a.ra}}};this.rc=function(){if(this.ta.length>0)for(object in this.ta)this.ta[object].Ia(n);this.ta=[];this.canvas.oa=
d};this.hd=function(a,b,c,f){this.ta=[];if(a>=c){var g=c,k=f;c=a;a=g;f=b;b=k}for(object in this.aa)if(this.aa[object]!=e)if(this.aa[object].ja>=a&&this.aa[object].ja<=c&&this.aa[object].ka>=b&&this.aa[object].ka<=f){this.ta.push(this.aa[object]);this.aa[object].Ia(d)}else this.aa[object].Ia(n);for(connection in this.ea)if(this.ea[connection]!=e){var t=Math.abs(this.ea[connection].da.object.ka+this.ea[connection].da.y-(this.ea[connection].fa.object.ka+this.ea[connection].fa.y));g=Math.abs(this.ea[connection].da.object.ja+
this.ea[connection].da.x-(this.ea[connection].fa.object.ja+this.ea[connection].fa.x));var u=this.ea[connection].fa.object.ka+this.ea[connection].fa.y;k=this.ea[connection].fa.object.ja+this.ea[connection].fa.x;var w=this.ea[connection].da.object.ka+this.ea[connection].da.y,y=this.ea[connection].da.object.ja+this.ea[connection].da.x;if(u>w)u=w;if(k>y)k=y;t=u+t/2;g=k+g/2;if(g>=a&&g<=c&&t>=b&&t<=f){this.ta.push(this.ea[connection]);this.ea[connection].Ia(d)}else this.ea[connection].Ia(n)}};this.jd=function(){if(this.aa.length==
0)return e;B&&console.log("save@jspd.controller","objects",this.aa);B&&console.log("save@jspd.controller","connections",this.ea);var a=[];a=a.concat(this.aa,this.ea);var b=[];for(elmt in a)if(a[elmt]!=e)if(a[elmt].label!="save"){var c;D.prototype=a[elmt];c=new D;c.Pb();b.push(c)}return I(b)};this.load=function(a){var b=e;try{b=eval(a)}catch(c){console.log(c,a)}this.empty();B&&console.log("load@jspd.controller",b);for(obj in b){B&&console.log("load@jspd.controller","--------- loop add ---------",b[obj]);
if(b[obj].ua=="connection"){B&&console.log("load@jspd.controller","--------- connection");b[obj].ga=this;b[obj].$a()}else{B&&console.log("load@jspd.controller","--------- object");b[obj].ga=this;b[obj].$a();B&&console.log("load@jspd.controller","add",b[obj]);this.add(b[obj],b[obj].ja,b[obj].ka)}}};this.bc=function(a){for(obj in this.aa){for(inlet in this.aa[obj].ba)if(this.aa[obj].ba[inlet].label==a)return this.aa[obj].ba[inlet];for(outlet in this.aa[obj].ca)if(this.aa[obj].ca[outlet].label==a)return this.aa[obj].ca[outlet]}};
this.ic=function(){var a=document.getElementById("jspd");a.setAttribute("style","display:none");var b=document.createElement("div");b.setAttribute("id","jspd_maximizer");b.appendChild(document.createTextNode("jspd"));b.addEventListener("click",function(){a.setAttribute("style","display:block");document.body.removeChild(b)},n);document.body.appendChild(b)}};if(typeof A.view=="undefined")A.view={};
A.view.toolbar=function(a){this.yc=a;this.qb=function(){var b=document.createElement("div");b.setAttribute("class","toolbar");for(button in this.yc){var c=document.createElement("div");c.setAttribute("class","button");c.addEventListener("click",a[button][1],n);c.appendChild(document.createTextNode(a[button][0]));b.appendChild(c)}return b};return this.qb()};if(typeof A=="undefined")A={};if(typeof A.view=="undefined")A.view={};
A.view.bd=function(a){this.ga=a;this.Ha=this.view=e;this.sa=[];this.fc=this.Sa=e;this.Ib=function(){var b=document.createElement("div");b.setAttribute("style","position:relative;height:30px;");document.createElement("div").setAttribute("style","float:left;color:#777;padding-bottom:5px;font-size:16px;");var c=this,f=[];f.push(["Minimize",function(){c.ga.ic()}]);f.push(["Save",function(){c.ga.aa.length==0?alert("Empty patch"):c.save()}]);f.push(["Save as ...",function(){c.ga.aa.length==0?alert("Empty patch"):
c.nc()}]);f.push(["Library",function(){var g=document.createElement("div"),k=document.createElement("div"),t=document.createElement("div");c.Ha=t;k.appendChild(t);g.appendChild(k);k=document.createElement("div");k.setAttribute("style","font-size:20px;padding:10px;");k.appendChild(document.createTextNode("Patch"));k.appendChild(g);var u=new C(k,c.ga.db);g=[];g.push(["<<",function(){u.close()}]);g.push(["Rename",o()]);g.push(["Delete",function(){if(c.Ha.selectedIndex==-1)alert("No patch selected");
else{var w=c.sa.sa[c.Ha.selectedIndex].Oa("id");confirm("Delete "+c.sa.sa[c.Ha.selectedIndex].Oa("name")+" ?")&&(new A.wa.ab(w)).$b(A.Za.pb(c,c.oa))}}]);g.push(["Delete all",function(){if(confirm("Delete all ?")){(new A.wa.ab).$b(A.Za.pb(c,c.oa));u.close()}}]);u.toolbar=new A.view.toolbar(g);u.open();c.oa(e,function(){u.close()})}]);f=new A.view.toolbar(f);b.appendChild(f);f=document.createElement("div");f.setAttribute("style","clear:both");b.appendChild(f);this.ga.db.appendChild(b);this.view=b;b.appendChild(document.createElement("div"))};
this.show=function(){this.view.style.display="block"};this.yd=function(){this.view.style.display="none"};this.nc=function(){var b=document.createElement("div"),c=document.createElement("div");c.setAttribute("style","float:left;padding:5px");c.appendChild(document.createTextNode("Patch name"));b.appendChild(c);var f=document.createElement("input");f.setAttribute("style","font-size:20px;");b.appendChild(f);b.setAttribute("style","font-size:20px;padding:10px;");var g=new C(b,this.ga.db),k=this;b=[];
b.push(["Cancel",function(){g.close()}]);b.push(["Save",function(){if(f.value=="")alert("Invalid patch name");else{k.Sa=e;k.save(f.value);g.close()}}]);g.toolbar=new A.view.toolbar(b);g.open()};this.save=function(b){if(this.ga.aa.length==0)alert("Empty patch");else if(this.Sa==e&&b==e)this.nc();else{var c=new A.wa.ab;if(this.Sa!=e)c.id=this.Sa;else c.Ra("name",b);b=this.ga.jd();c.Ra("data",b.replace(RegExp('"',"g"),'"'));c.Ra("timestamp",(new Date).getTime());c.save(A.Za.pb(this,this.oa))}};this.pc=
s("Sa");this.ad=s("fc");this.oa=function(b,c){b!=e&&this.pc(b);var f=document.createElement("select");f.setAttribute("style","background-color:#000;color:#FFF;border:1px solid #000;font-size:20px;width:250px;");var g=this;g.sa=new A.wa.Cc(new A.wa.ab);g.sa.Mc(function(){var k=1,t=e,u=document.createElement("option"),w=document.createTextNode("---------------------");u.appendChild(w);for(f.appendChild(u);g.sa.next();){u=document.createElement("option");w=g.sa.item.Oa("id");var y=new Date;y.setTime(g.sa.item.Oa("timestamp"));
y=k+" - "+g.sa.item.Oa("name")+" ("+y.getDate()+"/"+y.getMonth()+"/"+y.getFullYear()+")";if(g.Sa==w||b==w)t=k;w=document.createTextNode(y);u.appendChild(w);f.appendChild(u);k++}if(t!=e)f.options[t].selected=d;f.addEventListener("change",function(){g.fc(g.sa.sa[this.selectedIndex-1].Oa("data"));g.pc(g.sa.sa[this.selectedIndex-1].Oa("id"));typeof c!="undefined"&&c()});if(g.Ha!=e){g.Ha.parentNode.appendChild(f);g.Ha.parentNode.removeChild(g.Ha)}g.Ha=f})};this.Ib()};if(typeof J=="undefined")var J={};
function C(a,b){this.content=a;this.Aa=b;this.toolbar=this.window=e;this.open=function(){if(this.Aa==e)this.Aa=document.body;var c=this.Aa.offsetWidth,f=this.Aa.offsetHeight,g=document.createElement("div");g.setAttribute("class","window");g.setAttribute("style","width:"+(c-20)+"px;height:"+(f-30)+"px");f=e;switch(typeof this.content){case "string":f=document.createTextNode(this.content);break;default:f=this.content}g.appendChild(f);this.Aa.appendChild(g);if(this.toolbar!=e){this.toolbar.style.position=
"absolute";this.toolbar.style.zIndex="1001";this.toolbar.style.width=c-2+"px";this.Aa.appendChild(this.toolbar)}this.window=g};this.close=function(){this.Aa.removeChild(this.window);this.Aa.removeChild(this.toolbar)}}if(typeof A.Za=="undefined")A.Za={};A.Za.pb=function(a,b){function c(){return arguments.callee.Kc.apply(arguments.callee.target,arguments)}c.target=a;c.Kc=b;return c};if(typeof K=="undefined")var K={};if(typeof L=="undefined")var L={};
A.port=function(){this.ua="port";this.object=e;this.ports=[];this.ea=[];this.y=this.x=this.value=e;this.bb=function(a){B&&console.log("connect@jspd.port","Connection ...",a.object);for(p in this.object.ba)if(this.object.ba[p]===a){B&&console.log("connect@jspd.port","inlet current");return n}for(p in this.object.ca)if(this.object.ca[p]===a){B&&console.log("connect@jspd.port","outlet current");return n}for(p in this.ports)if(this.ports[p]===a){B&&console.log("connect@jspd.port","this");return n}this.ports.push(a);
for(p in a.ports)if(a.ports[p]===this){B&&console.log("connect@jspd.port","rthis");return n}a.bb(this);B&&console.log("connect@jspd.port",this.label+"@"+this.object.label+" <--\> "+a.label+"@"+a.object.label);return d};this.nd=s("value");this.xd=z("value");this.send=function(a){for(port in this.ports)if(this.ports[port]!=e){B&&console.log("send@jspd.port",this.ports[port].object.label,a);this.ports[port].nd(a);this.ports[port].object.execute()}};this.Pb=function(){console.log(this.object.label);this.object=
e;this.ports=[];this.ea=[];this.y=this.x=this.value=e};this.$a=function(){this.ports=[];this.ea=[];B&&console.log("wakeup@jspd.port")}};A.da=function(a){A.port.call(this);this.ua="inlet";this.object=a;this.label="i#"+Math.random()};A.fa=function(a){A.port.call(this);this.ua="outlet";this.object=a;this.label="o#"+Math.random()};if(typeof A.wa=="undefined")A.wa={};A.wa.Ea=function(){try{if(window.openDatabase)return openDatabase("jspd_db","1.0","jsPD Database",2E5);else alert("Couldn't open the database.  Please try with a WebKit nightly with this feature enabled")}catch(a){alert(a)}return e};
if(typeof L=="undefined")L={};if(typeof A.object=="undefined")A.object={};
A.aa.pd=function(){A.aa.object.call(this);this.label="";this.ba=[];this.ca=[];this.Ga=function(){var a=document.createElement("input");a.setAttribute("id","input");a.setAttribute("style","width:90px;position:absolute;top:"+(this.ka+2)+"px;left:"+(this.ja+3)+"px");var b=this;a.addEventListener("keypress",function(c){if(H(c)=="13"){if(c.target.value!=e){for(var f=c.target.value.split(RegExp("[ ]+","g")),g=eval("new jspd.objects."+f[0]+"();"),k=1;k<f.length;k++)g.qc(k,f[k]);g.oc(b.ga);b.ga.add(g,b.ja,
b.ka);a.parentNode.removeChild(a);b.ga.remove(b)}a.removeEventListener("keypress",arguments.callee,n)}},n);this.ga.canvas.qb().parentNode.appendChild(a)}};if(typeof L=="undefined")L={};if(typeof A.aa=="undefined")A.aa={};
A.aa.object=function(){this.ua="jspd.objects.object";this.la=this.ya=this.height=this.width=this.ka=this.ja=this.ga=this.ca=this.ba=this.label=e;this.Ba=[];this.selected=n;this.label&&(this.label=this.label);this.inlets&&(this.ba=this.inlets);this.outlets&&(this.ca=this.outlets);this.qc=function(a,b){B&&console.log("setParam@jspd.objects.object",a,b);this.Ba[a]=b};this.Fa=function(a){return this.Ba[a]};this.Ic=function(){this.Ba=[]};this.oc=s("ga");this.zd=z("selected");this.Ia=function(a){this.selected=
a;this.la.Ia!=e&&this.la.Ia(a)};this.Vb=function(a,b){if(a+this.la.width>this.ga.canvas.canvas.width-4||b+this.la.height>this.ga.canvas.canvas.height-4||a<=4||b<=4)return n;return d};this.Ya=function(a,b){if(a<0)a=0.5;if(b<0)b=0.5;this.ja=a;this.ka=b;this.ga.canvas.md(this.ya,a,b);this.Wa();for(outlet in this.ca)for(connection in this.ca[outlet].ea)this.ca[outlet].ea[connection].Ya(e,e);for(inlet in this.ba)for(connection in this.ba[inlet].ea)this.ba[inlet].ea[connection].Ya(e,e);return d};this.Fa=
function(a){B&&console.log("getParam@jspd.objects.object",a);return this.Ba[a]};this.Gb=function(){var a=this.label;B&&console.log("getLabel@jspd.objects.object");for(param in this.Ba)if(this.Ba[param]!=e)a+=" "+this.Ba[param];return a};this.Nc=function(){var a=0,b=0;this.Ga();if(this.box!=e)this.la=this.box;B&&console.log("getBox@jspd.objects.object",this);if(this.la==e){this.la=new A.ia.la;this.la.zb(this.Gb());if(this.ba!=e&&this.ba.length>0){this.la.add(new A.ia.Ua(100,0),0,4);for(elmt in this.ba){this.la.add(new A.ia.La(10,
4),a*10,0);this.ba[elmt].x=a*10;this.ba[elmt].y=0;a++}}if(this.ca!=e&&this.ca.length>0){this.la.add(new A.ia.Ua(100,0),0,20);for(elmt in this.ca){this.la.add(new A.ia.La(10,4),b*10,20);this.ca[elmt].x=b*10;this.ca[elmt].y=20;B&&console.log("getBox@jspd.objects.object",this.ca[elmt]);b++}}}else{if(this.ba!=e&&this.ba.length>0)for(elmt in this.ba){this.ba[elmt].x=a*10;this.ba[elmt].y=0;a++}if(this.ca!=e&&this.ca.length>0)for(elmt in this.ca){this.ca[elmt].x=b*10;this.ca[elmt].y=20;b++}}return this.la};
this.dc=function(a,b){if(b-this.ka<=10)return this.ba[Math.floor((a-this.ja)/10)];if(b-this.ka>10)return this.ca[Math.floor((a-this.ja)/10)];return e};this.Pa=function(){B&&console.log("onMouseDown@jspd.objects.object");this.Zb()};this.Qa=function(){this.ga.canvas.ma.style.cursor=this.selected?"move":"crosshair"};this.execute=function(){B&&console.log("execute@jspd.objects.object")};this.Zb=function(){var a=document.createElement("input");a.setAttribute("id","input");a.setAttribute("style","font-size:16px;padding:5px;border:1px dashed #AAA;width:150px;position:absolute;top:"+
(this.ka+6)+"px;left:"+(this.ja+3)+"px");a.setAttribute("value",this.Gb());a.focus();var b=this;a.addEventListener("keypress",function(c){var f=H(c);if(f=="13"||f=="10"){if(c.target.value!=e){f=c.target.value.split(RegExp("[ ]+","g"));b.Ic();for(var g=1;g<f.length;g++)b.qc(g,f[g]);b.Mb();b.la.zb!=e&&b.la.zb(b.Gb());a.parentNode.removeChild(a);b.ga.canvas.oa=d}a.removeEventListener("keypress",arguments.callee,n)}},n);this.ga.canvas.qb().parentNode.appendChild(a)};this.remove=function(){for(outlet in this.ca)for(connection in this.ca[outlet].ea)this.ca[outlet].ea[connection].remove();
for(inlet in this.ba)for(connection in this.ba[inlet].ea)this.ba[inlet].ea[connection].remove()};this.Pb=function(){B&&console.log("sleep@jspd.objects.object");this.la=this.ga=e;for(var a=[],b=0;b<this.ba.length;b++){var c=new A.da(this);c.object=e;c.ports=[];c.ea=[];c.label=this.ba[b].label;c.x=this.ba[b].x;c.y=this.ba[b].y;a.push(c)}this.ba=a;a=[];for(b=0;b<this.ca.length;b++){c=new A.fa(this);c.object=e;c.ports=[];c.ea=[];c.label=this.ca[b].label;c.x=this.ca[b].x;c.y=this.ca[b].y;a.push(c)}this.ca=
a;this.Nb()};this.$a=function(){B&&console.log("wakeup@jspd.objects.object",this);for(inlet in this.ba)if(this.ba[inlet]!=e){this.ba[inlet].object=this;this.ba[inlet].$a()}for(outlet in this.ca)if(this.ca[outlet]!=e){this.ca[outlet].object=this;this.ca[outlet].$a()}if(this.Ba==e)this.Ba=[];this.Ga();this.yb()};this.Ga=o();this.Wa=o();this.Nb=o();this.yb=o();this.Mb=o()};if(typeof L=="undefined")L={};
A.zc=function(a){this.ua="connection";this.ga=a;this.selected=this.Ab=n;this.Cd=this.xb=this.wb=this.ya=this.ec=this.da=this.hc=this.fa=this.canvas=this.ka=this.ja=e;this.Ia=function(b){var c=this.ga.canvas.cc(this.ya);if(b){if(!this.selected){this.selected=d;if(c!=e)c.strokeStyle="rgba(255,0,0,1.0)";this.ga.canvas.ma.style.cursor="crosshair"}}else{this.selected=n;if(this.ya!=e)if(c!=e)c.strokeStyle="rgba(0,0,0,1.0)"}};this.Vb=function(){return d};this.Ya=function(){var b=this.ga.canvas.cc(this.ya);
if(b!=e){b.ja=this.fa.object.ja+this.fa.x+5;b.ka=this.fa.object.ka+this.fa.y+4;b.eb=this.da.object.ja+this.da.x+5;b.fb=this.da.object.ka+this.da.y}};this.kd=s("canvas");this.start=function(b){this.Ab=d;this.ja=b.object.ja+b.x+5;this.ka=b.object.ka+b.y+4;this.fa=b;var c=this;this.ga.canvas.ma.addEventListener("mousemove",this.wb=function(f){c.Qa(f)},n);this.ga.canvas.ma.addEventListener("touchmove",this.wb=function(f){c.Qa(f)},n);this.ga.canvas.ma.addEventListener("mouseup",this.xb=function(f){c.kb(f)},
n);this.ga.canvas.ma.addEventListener("touchend",this.xb=function(f){c.kb(f)},n)};this.Qa=function(b){if(this.Ab){b=E(b);this.ga.canvas.Gc(this.ja,this.ka,b.qa,b.ra)}};this.kb=function(b){if(this.Ab){this.ga.canvas.ma.removeEventListener("mousemove",this.wb,n);this.ga.canvas.ma.removeEventListener("touchmove",this.wb,n);this.ga.canvas.ma.removeEventListener("mouseup",this.xb,n);this.ga.canvas.ma.removeEventListener("touchend",this.xb,n);b=E(b);var c=this.ga.Hb(b.qa,b.ra);if(c!=e){b=c.dc(b.qa,b.ra);
if(b!=e&&F(b,"inlet")){this.da=b;this.bb()}}this.Ab=n}};this.bb=function(){if(this.da.bb(this.fa)){B&&console.log("connect@jspd.connection","connect",this.da,this.fa);this.da.ea.push(this);this.fa.ea.push(this);this.ya=this.canvas.add(new A.ia.Tb(this.da.x+this.da.object.ja+5,this.da.y+this.da.object.ka),this.fa.x+this.fa.object.ja+5,this.fa.y+this.fa.object.ka+4);this.canvas.oa=d;B&&console.log("connect@jspd.connection","connection.canvasidx",this.ya);this.ga.ea.push(this)}};this.remove=function(){B&&
console.log("remove@jspd.connection","in");for(p in this.da.ports)if(this.da.ports[p]===this.fa)this.da.ports[p]=e;for(p in this.fa.ports)if(this.fa.ports[p]===this.da)this.fa.ports[p]=e;B&&console.log("remove@jspd.connection",this.ya);this.canvas.remove(this.ya);this.ya=e};this.$a=function(){this.canvas=this.ga.canvas;B&&console.log("wakeup@jspd.connection",this,this.da);this.da=this.ga.bc(this.ec);this.fa=this.ga.bc(this.hc);this.bb()};this.Pb=function(){this.canvas=this.ga=e;this.hc=this.fa.label;
this.ec=this.da.label;this.da=this.fa=e}};if(typeof A.wa=="undefined")A.wa={};
A.wa.Cc=function(a){this.Ma=a;this.sa=[];this.cursor=-1;this.item=this.Ed=e;this.Mc=function(b){for(var c="SELECT ",f=0;f<this.Ma.Ja.length;f++){if(f>0)c+=",";c+=this.Ma.Ja[f][0]}c+=" FROM "+this.Ma.Ca;self=this;this.Ma.Ea.transaction(function(g){g.executeSql(c,[],function(k,t){for(var u=0;u<t.rows.length;u++){var w=new A.wa.ab;w.Ra("id",t.rows.item(u).id);w.Ra("name",t.rows.item(u).name);w.Ra("data",t.rows.item(u).data);w.Ra("timestamp",t.rows.item(u).timestamp);self.sa.push(w)}b()},function(){self.Ma.Bc()})})};
this.next=function(){if(this.cursor+1>=this.sa.length)return n;this.cursor++;this.item=this.sa[this.cursor];return d}};if(typeof A.wa=="undefined")A.wa={};
A.wa.Ma=function(){this.id=this.Ea=e;this.Ja=[];this.Bb=[];this.Ca=e;this.Ka=[];this.load=function(){for(var a="SELECT ",b=0;b<this.Ja.length;b++){if(b>0)a+=",";a+=this.Ja[b][0]}a+=" FROM "+this.Ca;a+=" WHERE id = "+this.id+";";this.Ea.transaction(function(c){c.executeSql(a,[],function(f,g){for(var k=0;k<g.rows.length;k++)console.log("RES:"+f+"->"+g.rows.item(k).id+"-"+g.rows.item(k).data)},function(f,g){console.log(f,g)})})};this.save=function(a){var b=[],c=e;if(this.id!=e){c="UPDATE "+this.Ca+" SET ";
for(var f=0;f<this.Ka.length;f++){if(f>0)c+=",";c+=this.Ka[f]+"=? ";b.push(this.Bb[this.Ka[f]])}c+=" WHERE id = "+this.id+";"}else{c="INSERT INTO "+this.Ca+"(";for(f=0;f<this.Ka.length;f++){if(f>0)c+=",";c+=this.Ka[f]}c+=") VALUES(";for(f=0;f<this.Ka.length;f++){if(f>0)c+=",";c+="?";b.push(this.Bb[this.Ka[f]])}c+=");"}var g=this;this.Ea.transaction(function(k){k.executeSql(c,b,function(t,u){if(g.id==e)g.id=u.insertId;a(g.id)},function(t,u){console.log(t,u)})})};this.Ra=function(a,b){this.Ka.push(a);
this.Bb[a]=b};this.Oa=function(a){return this.Bb[a]};this.wd=function(){var a="SELECT MAX(id)+1 as nextid FROM "+this.Ca,b=this;this.Ea.transaction(function(c){c.executeSql(a,[],function(f,g){for(var k=0;k<g.rows.length;k++){console.log("RES:"+f+"->"+g.rows.item(k).nextid);b.id=g.rows.item(k).nextid}},function(f,g){console.log(f,g)})})};this.Bc=function(){for(var a="CREATE TABLE "+this.Ca+"(",b=0;b<this.Ja.length;b++){if(b>0)a+=",";a+=this.Ja[b][0]+" "+this.Ja[b][1]}a+=");";this.Ea.transaction(function(c){c.executeSql(a,
[],function(f,g){console.log("CREATE TABLE",f,g)},function(f,g){console.log("CREATE TABLE",f,g)})})};this.sd=function(){var a=this;this.Ea.transaction(function(b){b.executeSql("DROP TABLE "+a.Ca+";",[],function(c,f){console.log("DROP TABLE",c,f)},function(c,f){console.log("DROP TABLE",c,f)})})};this.$b=function(a){var b=this;this.Ea.transaction(function(c){c.executeSql("DELETE FROM "+b.Ca+";",[],function(f,g){console.log("DELETE TABLE",f,g);a()},function(f,g){console.log("DELETE TABLE",f,g)})})}};
A.wa.ab=function(){A.wa.Ma.call(this);this.Ea=new A.wa.Ea;this.Ca="patch";this.Ja=[["id","INTEGER PRIMARY KEY AUTOINCREMENT"],["name","TEXT"],["data","TEXT"],["timestamp","REAL"]]};if(typeof A=="undefined")A={};if(typeof A.ia=="undefined")A.ia={};
A.ia.object=function(){this.ua="jspd.graphics.object";this.elements=[];this.selected=n;this.Ia=s("selected");this.add=function(a,b,c){a.ja=b;a.ka=c;this.elements.push(a);return this.elements.length};this.cc=function(a){return this.elements[a-1]};this.Ya=function(a,b){this.ja=a;this.ka=b};this.md=function(a,b,c){this.elements[a-1].Ya(b,c)};this.remove=function(a){B&&console.log("remove@jspd.graphics.canvas",a);this.elements[a-1]=e};this.lc=function(){B&&console.log("removeall@jspd.graphics.canvas");
for(elmt in this.elements)this.elements[elmt]=e};this.cb=function(a,b,c){this.za(a,b,c);this.selected&&this.$c(a,b,c)};this.za=o();this.$c=function(a,b,c){var f=new A.ia.Ua(10,0);f.strokeStyle="rgba(255,0,0,0.5)";f.za(a,b-3,c-3);f=new A.ia.Ua(0,10);f.strokeStyle="rgba(255,0,0,0.5)";f.za(a,b-3,c-3)}};
A.ia.canvas=function(a){A.ia.object.call(this);this.ua="jspd.graphics.canvas";this.Aa=e;this.canvas=a;this.Na=this.ma=this.ob=e;this.oa=n;this.Ib=function(){if(this.canvas)if(this.canvas.getContext)if(this.ob=this.canvas.getContext("2d")){this.Aa=this.canvas.parentNode;if(this.ma=document.createElement("canvas")){this.ma.id="imageTemp";this.ma.width=this.canvas.width;this.ma.height=this.canvas.height;this.Aa.appendChild(this.ma);this.Na=this.ma.getContext("2d")}else alert("Error: I cannot create a new canvas element!")}else alert("Error: failed to getContext!");
else alert("Error: no canvas.getContext!");else alert("Error: I cannot find the canvas element!")};this.qb=z("canvas");this.ud=z("ma");this.getContext=z("Na");this.cb=function(){if(this.oa){this.ob.clearRect(0,0,this.canvas.width,this.canvas.height);for(a in this.elements)this.elements[a]!=e&&this.elements[a].cb(this.ob,this.elements[a].ja,this.elements[a].ka);this.oa=n}};this.cd=function(){this.cb()};this.Gc=function(b,c,f,g){this.Na.clearRect(0,0,this.canvas.width,this.canvas.height);(new A.ia.Tb(f,
g)).cb(this.Na,b,c)};this.Hc=function(b,c,f,g){this.Na.clearRect(0,0,this.canvas.width,this.canvas.height);f=new A.ia.La(f,g);f.strokeStyle="rgba(200,200,200,1.0)";f.fillStyle="rgba(255,255,255,0.0)";f.cb(this.Na,b,c)}};
A.ia.La=function(a,b){A.ia.object.call(this);this.elements=[];this.ua="jspd.graphics.rectangle";this.width=a;this.height=b;this.strokeStyle="rgba(0,0,0,1.0)";this.fillStyle="rgba(255,255,255,1.0)";this.za=function(c,f,g){c.save();c.beginPath();c.strokeStyle=this.strokeStyle;c.fillStyle=this.fillStyle;c.rect(f,g,this.width,this.height);c.fill();c.stroke();for(elmt in this.elements)this.elements[elmt]!=e&&this.elements[elmt].za(c,f+this.elements[elmt].ja,g+this.elements[elmt].ka);c.restore()}};
A.ia.Ua=function(a,b){A.ia.object.call(this);this.ua="jspd.graphics.line";this.eb=a;this.fb=b;this.strokeStyle="rgba(0,0,0,1.0)";this.za=function(c,f,g){c.save();c.beginPath();c.strokeStyle=this.strokeStyle;c.moveTo(f,g);c.lineTo(f+this.eb,g+this.fb);c.stroke();c.closePath();c.restore()}};
A.ia.Tb=function(a,b){A.ia.object.call(this);this.ua="jspd.graphics.bezier";this.eb=a;this.fb=b;this.strokeStyle="rgba(0,0,0,1.0)";this.za=function(c,f,g){c.save();c.beginPath();c.strokeStyle=this.strokeStyle;c.moveTo(f,g);c.bezierCurveTo(f,g+20,this.eb,this.fb-20,this.eb,this.fb);c.stroke();c.closePath();c.restore()}};A.ia.text=function(a){A.ia.object.call(this);this.ua="jspd.graphics.text";this.text=a;this.za=function(b,c,f){b.save();b.font="12px sans-serif";b.fillText(this.text,c,f);b.restore()}};
A.ia.la=function(){A.ia.object.call(this);this.sb=e;this.elements=[];this.width=100;this.height=24;this.ua="jspd.graphics.box";this.zb=function(a){a=new A.ia.text(a);a.ja=5;a.ka=15;this.sb=a};this.za=function(a,b,c){box=new A.ia.La(this.width,this.height);box.fillStyle="rgba(255,255,255,0.0)";box.za(a,b,c);for(M in this.elements)this.elements[M].za(a,b+this.elements[M].ja,c+this.elements[M].ka);this.sb.za(a,b+this.sb.ja,c+this.sb.ka)}};
A.ia.nb=function(a,b){this.ua="jspd.graphics.circle";this.za=function(c,f,g){c.save();c.strokeStyle="#000000";if(b!=e)c.fillStyle=b;c.beginPath();c.arc(f+a,g+a,a,0,Math.PI*2,d);c.closePath();c.stroke();c.fill();c.restore()}};window.Cb=window.Cb||{};
window.Cb.tc={Jc:{arial:["liberation sans","nimbus sans l","freesans","optimer","dejavu sans"],"times new roman":["liberation serif","helvetiker","linux libertine","freeserif"],"courier new":["dejavu sans mono","liberation mono","nimbus mono l","freemono"],georgia:["nimbus roman no9 l","helvetiker"],helvetica:["nimbus sans l","helvetiker","freesans"],tahoma:["dejavu sans","optimer","bitstream vera sans"],verdana:["dejavu sans","optimer","bitstream vera sans"]},Lc:{serif:["times new roman","georgia",
"garamond","bodoni","minion web","itc stone serif","bitstream cyberbit"],"sans-serif":["arial","verdana","trebuchet","tahoma","helvetica","itc avant garde gothic","univers","futura","gill sans","akzidenz grotesk","attika","typiko new era","itc stone sans","monotype gill sans 571"],monospace:["courier","courier new","prestige","everson mono"],cursive:["caflisch script","adobe poetica","sanvito","ex ponto","snell roundhand","zapf-chancery"],fantasy:["alpha geometrique","critter","cottonwood","fb reactor",
"studz"]},va:{},Ob:0.962,Eb:{}};
(function(){function a(h){switch(String(h)){case "bolder":case "bold":case "900":case "800":case "700":return"bold";default:case "normal":return"normal"}}function b(h){if(document.defaultView&&document.defaultView.getComputedStyle)return document.defaultView.getComputedStyle(h,e);return h.currentStyle||h.style}function c(){if(!k.xa)for(var h=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}],l=0;l<
h.length;l++)try{k.xa=h[l]();break}catch(j){}return k.xa}var f=window.opera&&/Opera\/9/.test(navigator.userAgent),g=window.sc?window.sc.prototype:document.createElement("canvas").getContext("2d").__proto__,k=window.Cb.tc;k.options={Fb:" ",Fc:n,dd:n,Dc:n,Sb:n};var t=document.getElementsByTagName("script");t=t[t.length-1].src.split("?");k.xc=t[0].substr(0,t[0].lastIndexOf("/")+1);if(t[1]){t=t[1].split("&");for(var u=t.length-1;u>=0;--u){var w=t[u].split("=");k.options[w[0]]=w[1]}}var y=!k.options.Fc&&
g.Ad&&!g.fillText;if(g.fillText&&!k.options.dd&&!/iphone/i.test(navigator.userAgent))return window.uc={hb:o()};k.gc=function(h){var l=this.va,j,m,q=this.Jc,r=this.Lc;if(l[h])return l[h];if(r[h])for(j=0;j<r[h].length;j++)if(m=this.gc(r[h][j]))return m;if(!(m=q[h]))return n;for(j=0;j<m.length;j++)if(h=l[m[j]])return h;return n};k.Oc=function(h,l,j){var m=this.gc(h);if(!m)return n;if(m&&m[l]&&m[l][j])return m[l][j];if(!this.options.Sb)return n;m=this.xa;var q=this.xc+this.options.Sb+"/"+(h.replace(/[ -]/g,
"_")+"-"+l+"-"+j)+".js";m=c();m.open("get",q,n);m.send(e);if(m.status==200){eval(m.responseText);return this.va[h][l][j]}else throw"Unable to load the font ["+h+" "+l+" "+j+"]";};k.hb=function(h){var l=h.td.toLowerCase();this.va[l]=this.va[l]||{};if(h.Qb){this.va[l].Va=this.va[l].Va||{};this.va[l].Va.Va=h;this.va[l].Va.Uc=h;this.va[l].bold=this.va[l].Va||{};this.va[l].bold.Va=h;this.va[l].bold.Uc=h}else{this.va[l][h.Xb]=this.va[l][h.Xb]||{};this.va[l][h.Xb][h.rd]=h}return h};window.uc={va:k.va,hb:k.hb};
k.rb=function(h){var l=a(h.Rb),j=h.ac,m,q;for(m=0;m<j.length;m++)if(q=this.Oc(j[m].toLowerCase().replace(/^-webkit-/,""),l,h.style))return q;return n};try{g.font="10px sans-serif";g.textAlign="start";g.textBaseline="alphabetic"}catch(U){}g.jc=function(h){if(k.Eb[h])return this.getComputedStyle(k.Eb[h]);var l={},j;if(!this.lb){this.lb=document.createElement("span");this.canvas.appendChild(this.lb)}this.canvas.font="10px sans-serif";this.lb.style.font=h;j=b(this.lb);l.size=j.fontSize;l.Rb=a(j.fontWeight);
l.style=j.fontStyle;j=j.fontFamily.split(",");for(i=0;i<j.length;i++)j[i]=j[i].replace(/^["'\s]*/,"").replace(/["'\s]*$/,"");l.ac=j;return this.getComputedStyle(k.Eb[h]=l)};g.Ub=function(h){return h.style+" "+h.Rb+" "+h.size+'px "'+h.ac+'"'};g.gd=function(h,l){var j=k.rb(l),m=l.size/j.mc*0.75,q=0,r,x=String(h).split(""),v=x.length;if(!f){this.scale(m,-m);this.lineWidth/=m}for(r=0;r<v;r++)q+=this.fd(x[r],j,m,q)};g.fd=f?function(h,l,j,m){var q,r,x,v=l.gb[h]||l.gb[k.options.Fb];if(v){if(v.Kb){l=v.Db||
(v.Db=v.Kb.split(" "));x=l.length;for(h=0;h<x;){q=l[h++];switch(q){case "m":this.moveTo(l[h++]*j+m,l[h++]*-j);break;case "l":this.lineTo(l[h++]*j+m,l[h++]*-j);break;case "q":q=l[h++]*j+m;r=l[h++]*-j;this.quadraticCurveTo(l[h++]*j+m,l[h++]*-j,q,r);break;case "b":q=l[h++]*j+m;r=l[h++]*-j;ctx.bezierCurveTo(l[h++]*j+m,l[h++]*-j,l[h++]*j+m,l[h++]*-j,q,r)}}}return v.Ta*j}}:function(h,l){var j,m,q,r,x,v=l.gb[h]||l.gb[k.options.Fb];if(v){if(v.Kb){r=v.Db||(v.Db=v.Kb.split(" "));x=r.length;for(j=0;j<x;){m=
r[j++];switch(m){case "m":this.moveTo(r[j++],r[j++]);break;case "l":this.lineTo(r[j++],r[j++]);break;case "q":m=r[j++];q=r[j++];this.quadraticCurveTo(r[j++],r[j++],m,q);break;case "b":m=r[j++];q=r[j++];ctx.bezierCurveTo(r[j++],r[j++],r[j++],r[j++],m,q)}}}v.Ta&&this.translate(v.Ta,0)}};g.Pc=function(h,l){var j=0,m=0,q=k.rb(l),r,x=h.length,v;for(r=0;r<x;r++){v=q.gb[h.charAt(r)]||q.gb[k.options.Fb];j+=Math.max(v.Ta,v.Gd);m+=v.Ta}return{width:j,height:q.lineHeight,Ta:m}};g.getComputedStyle=function(h){var l,
j=b(this.canvas),m={},q=h.size;j=parseFloat(j.fontSize);var r=parseFloat(q);for(l in h)m[l]=h[l];m.size=typeof q==="number"||q.indexOf("px")!=-1?r:q.indexOf("em")!=-1?j*r:q.indexOf("%")!=-1?j/100*r:q.indexOf("pt")!=-1?r/0.75:j;return m};g.Qc=function(h,l,j){var m=b(this.canvas);h=this.measureText(h);l=l.size/j.mc*0.75;var q={x:0,y:0,Xc:h,scale:l};switch(this.textAlign){case "center":q.x=-h.width/2;break;case "right":q.x=-h.width;break;case "start":q.x=m.direction=="rtl"?-h.width:0;break;case "end":q.x=
m.direction=="ltr"?-h.width:0}switch(this.textBaseline){case "alphabetic":break;default:case e:case "ideographic":case "bottom":q.y=j.Ec;break;case "hanging":case "top":q.y=j.vc;break;case "middle":q.y=(j.vc+j.Ec)/2}q.y*=l;return q};g.Yb=function(h,l,j,m,q){m=this.jc(this.font);var r=k.rb(m),x=this.Qc(h,m,r);this.save();this.translate(l+x.x,j+x.y);if(r.Qb&&!q)this.strokeStyle=this.fillStyle;this.lineCap="round";this.beginPath();if(y){this.Zc=this.Ub(m);this[q?"mozPathText":"mozDrawText"](h)}else{this.scale(k.Ob,
k.Ob);this.gd(h,m);if(r.Qb)this.lineWidth=2+m.size*(m.Rb=="bold"?0.08:0.015)/2}this[q||r.Qb&&!y?"stroke":"fill"]();this.closePath();this.restore();if(k.options.Dc){h=Math.floor(x.x+l)+0.5;j=Math.floor(j)+0.5;this.save();this.strokeStyle="#F00";this.lineWidth=0.5;this.beginPath();this.moveTo(h+x.Xc.width,j);this.lineTo(h,j);this.moveTo(h-x.x,j+x.y);this.lineTo(h-x.x,j+x.y-m.size);this.stroke();this.closePath();this.restore()}};g.fillText=function(h,l,j,m){this.Yb(h,l,j,m,n)};g.strokeText=function(h,
l,j,m){this.Yb(h,l,j,m,d)};g.measureText=function(h){var l=this.jc(this.font),j={width:0};if(y){this.Zc=this.Ub(l);j.width=this.Bd(h)}else{var m=k.rb(l);m=l.size/m.mc*0.75;j.width=this.Pc(h,l).Ta*m*k.Ob}return j}})();if(typeof N=="undefined")var N={};
N&&N.hb&&N.hb({glyphs:{" ":{ha:10,s:"",x_min:0,x_max:10},"!":{ha:10,o:"m 5 21 l 5 7 m 5 2 l 4 1 l 5 0 l 6 1 l 5 2 ",x_min:4,x_max:6},'"':{ha:16,o:"m 4 21 l 4 14 m 12 21 l 12 14 ",x_min:4,x_max:12},"#":{ha:21,o:"m 11 25 l 4 -7 m 17 25 l 10 -7 m 4 12 l 18 12 m 3 6 l 17 6 ",x_min:3,x_max:18},$:{ha:20,o:"m 8 25 l 8 -4 m 12 25 l 12 -4 m 17 18 l 15 20 l 12 21 l 8 21 l 5 20 l 3 18 l 3 16 l 4 14 l 5 13 l 7 12 l 13 10 l 15 9 l 16 8 l 17 6 l 17 3 l 15 1 l 12 0 l 8 0 l 5 1 l 3 3 ",x_min:3,x_max:17},"%":{ha:24,
o:"m 21 21 l 3 0 m 8 21 l 10 19 l 10 17 l 9 15 l 7 14 l 5 14 l 3 16 l 3 18 l 4 20 l 6 21 l 8 21 m 17 7 l 15 6 l 14 4 l 14 2 l 16 0 l 18 0 l 20 1 l 21 3 l 21 5 l 19 7 l 17 7 ",x_min:3,x_max:21},"&":{ha:26,o:"m 23 12 l 23 13 l 22 14 l 21 14 l 20 13 l 19 11 l 17 6 l 15 3 l 13 1 l 11 0 l 7 0 l 5 1 l 4 2 l 3 4 l 3 6 l 4 8 l 5 9 l 12 13 l 13 14 l 14 16 l 14 18 l 13 20 l 11 21 l 9 20 l 8 18 l 8 16 l 9 13 l 11 10 l 16 3 l 18 1 l 20 0 l 22 0 l 23 1 l 23 2 ",x_min:3,x_max:23},"'":{ha:10,o:"m 5 19 l 4 20 l 5 21 l 6 20 l 6 18 l 5 16 l 4 15 ",
x_min:4,x_max:6},"(":{ha:14,o:"m 11 25 l 9 23 l 7 20 l 5 16 l 4 11 l 4 7 l 5 2 l 7 -2 l 9 -5 l 11 -7 ",x_min:4,x_max:11},")":{ha:14,o:"m 3 25 l 5 23 l 7 20 l 9 16 l 10 11 l 10 7 l 9 2 l 7 -2 l 5 -5 l 3 -7 ",x_min:3,x_max:10},"*":{ha:16,o:"m 8 21 l 8 9 m 3 18 l 13 12 m 13 18 l 3 12 ",x_min:3,x_max:13},"+":{ha:26,o:"m 13 18 l 13 0 m 4 9 l 22 9 ",x_min:4,x_max:22},",":{ha:10,o:"m 6 1 l 5 0 l 4 1 l 5 2 l 6 1 l 6 -1 l 5 -3 l 4 -4 ",x_min:4,x_max:6},"-":{ha:26,o:"m 4 9 l 22 9 ",x_min:4,x_max:22},".":{ha:10,
o:"m 5 2 l 4 1 l 5 0 l 6 1 l 5 2 ",x_min:4,x_max:6},"/":{ha:22,o:"m 20 25 l 2 -7 ",x_min:2,x_max:20},"0":{ha:20,o:"m 9 21 l 6 20 l 4 17 l 3 12 l 3 9 l 4 4 l 6 1 l 9 0 l 11 0 l 14 1 l 16 4 l 17 9 l 17 12 l 16 17 l 14 20 l 11 21 l 9 21 ",x_min:3,x_max:17},"1":{ha:20,o:"m 6 17 l 8 18 l 11 21 l 11 0 ",x_min:6,x_max:11},"2":{ha:20,o:"m 4 16 l 4 17 l 5 19 l 6 20 l 8 21 l 12 21 l 14 20 l 15 19 l 16 17 l 16 15 l 15 13 l 13 10 l 3 0 l 17 0 ",x_min:3,x_max:17},"3":{ha:20,o:"m 5 21 l 16 21 l 10 13 l 13 13 l 15 12 l 16 11 l 17 8 l 17 6 l 16 3 l 14 1 l 11 0 l 8 0 l 5 1 l 4 2 l 3 4 ",
x_min:3,x_max:17},"4":{ha:20,o:"m 13 21 l 3 7 l 18 7 m 13 21 l 13 0 ",x_min:3,x_max:18},"5":{ha:20,o:"m 15 21 l 5 21 l 4 12 l 5 13 l 8 14 l 11 14 l 14 13 l 16 11 l 17 8 l 17 6 l 16 3 l 14 1 l 11 0 l 8 0 l 5 1 l 4 2 l 3 4 ",x_min:3,x_max:17},"6":{ha:20,o:"m 16 18 l 15 20 l 12 21 l 10 21 l 7 20 l 5 17 l 4 12 l 4 7 l 5 3 l 7 1 l 10 0 l 11 0 l 14 1 l 16 3 l 17 6 l 17 7 l 16 10 l 14 12 l 11 13 l 10 13 l 7 12 l 5 10 l 4 7 ",x_min:4,x_max:17},"7":{ha:20,o:"m 17 21 l 7 0 m 3 21 l 17 21 ",x_min:3,x_max:17},
"8":{ha:20,o:"m 8 21 l 5 20 l 4 18 l 4 16 l 5 14 l 7 13 l 11 12 l 14 11 l 16 9 l 17 7 l 17 4 l 16 2 l 15 1 l 12 0 l 8 0 l 5 1 l 4 2 l 3 4 l 3 7 l 4 9 l 6 11 l 9 12 l 13 13 l 15 14 l 16 16 l 16 18 l 15 20 l 12 21 l 8 21 ",x_min:3,x_max:17},"9":{ha:20,o:"m 16 14 l 15 11 l 13 9 l 10 8 l 9 8 l 6 9 l 4 11 l 3 14 l 3 15 l 4 18 l 6 20 l 9 21 l 10 21 l 13 20 l 15 18 l 16 14 l 16 9 l 15 4 l 13 1 l 10 0 l 8 0 l 5 1 l 4 3 ",x_min:3,x_max:16},":":{ha:10,o:"m 5 14 l 4 13 l 5 12 l 6 13 l 5 14 m 5 2 l 4 1 l 5 0 l 6 1 l 5 2 ",
x_min:4,x_max:6},";":{ha:10,o:"m 5 14 l 4 13 l 5 12 l 6 13 l 5 14 m 6 1 l 5 0 l 4 1 l 5 2 l 6 1 l 6 -1 l 5 -3 l 4 -4 ",x_min:4,x_max:6},"<":{ha:24,o:"m 20 18 l 4 9 l 20 0 ",x_min:4,x_max:20},"=":{ha:26,o:"m 4 12 l 22 12 m 4 6 l 22 6 ",x_min:4,x_max:22},">":{ha:24,o:"m 4 18 l 20 9 l 4 0 ",x_min:4,x_max:20},"?":{ha:18,o:"m 3 16 l 3 17 l 4 19 l 5 20 l 7 21 l 11 21 l 13 20 l 14 19 l 15 17 l 15 15 l 14 13 l 13 12 l 9 10 l 9 7 m 9 2 l 8 1 l 9 0 l 10 1 l 9 2 ",x_min:3,x_max:15},"@":{ha:27,o:"m 18 13 l 17 15 l 15 16 l 12 16 l 10 15 l 9 14 l 8 11 l 8 8 l 9 6 l 11 5 l 14 5 l 16 6 l 17 8 m 12 16 l 10 14 l 9 11 l 9 8 l 10 6 l 11 5 m 18 16 l 17 8 l 17 6 l 19 5 l 21 5 l 23 7 l 24 10 l 24 12 l 23 15 l 22 17 l 20 19 l 18 20 l 15 21 l 12 21 l 9 20 l 7 19 l 5 17 l 4 15 l 3 12 l 3 9 l 4 6 l 5 4 l 7 2 l 9 1 l 12 0 l 15 0 l 18 1 l 20 2 l 21 3 m 19 16 l 18 8 l 18 6 l 19 5 ",
x_min:3,x_max:24},A:{ha:18,o:"m 9 21 l 1 0 m 9 21 l 17 0 m 4 7 l 14 7 ",x_min:1,x_max:17},B:{ha:21,o:"m 4 21 l 4 0 m 4 21 l 13 21 l 16 20 l 17 19 l 18 17 l 18 15 l 17 13 l 16 12 l 13 11 m 4 11 l 13 11 l 16 10 l 17 9 l 18 7 l 18 4 l 17 2 l 16 1 l 13 0 l 4 0 ",x_min:4,x_max:18},C:{ha:21,o:"m 18 16 l 17 18 l 15 20 l 13 21 l 9 21 l 7 20 l 5 18 l 4 16 l 3 13 l 3 8 l 4 5 l 5 3 l 7 1 l 9 0 l 13 0 l 15 1 l 17 3 l 18 5 ",x_min:3,x_max:18},D:{ha:21,o:"m 4 21 l 4 0 m 4 21 l 11 21 l 14 20 l 16 18 l 17 16 l 18 13 l 18 8 l 17 5 l 16 3 l 14 1 l 11 0 l 4 0 ",
x_min:4,x_max:18},E:{ha:19,o:"m 4 21 l 4 0 m 4 21 l 17 21 m 4 11 l 12 11 m 4 0 l 17 0 ",x_min:4,x_max:17},F:{ha:18,o:"m 4 21 l 4 0 m 4 21 l 17 21 m 4 11 l 12 11 ",x_min:4,x_max:17},G:{ha:21,o:"m 18 16 l 17 18 l 15 20 l 13 21 l 9 21 l 7 20 l 5 18 l 4 16 l 3 13 l 3 8 l 4 5 l 5 3 l 7 1 l 9 0 l 13 0 l 15 1 l 17 3 l 18 5 l 18 8 m 13 8 l 18 8 ",x_min:3,x_max:18},H:{ha:22,o:"m 4 21 l 4 0 m 18 21 l 18 0 m 4 11 l 18 11 ",x_min:4,x_max:18},I:{ha:8,o:"m 4 21 l 4 0 ",x_min:4,x_max:4},J:{ha:16,o:"m 12 21 l 12 5 l 11 2 l 10 1 l 8 0 l 6 0 l 4 1 l 3 2 l 2 5 l 2 7 ",
x_min:2,x_max:12},K:{ha:21,o:"m 4 21 l 4 0 m 18 21 l 4 7 m 9 12 l 18 0 ",x_min:4,x_max:18},L:{ha:17,o:"m 4 21 l 4 0 m 4 0 l 16 0 ",x_min:4,x_max:16},M:{ha:24,o:"m 4 21 l 4 0 m 4 21 l 12 0 m 20 21 l 12 0 m 20 21 l 20 0 ",x_min:4,x_max:20},N:{ha:22,o:"m 4 21 l 4 0 m 4 21 l 18 0 m 18 21 l 18 0 ",x_min:4,x_max:18},O:{ha:22,o:"m 9 21 l 7 20 l 5 18 l 4 16 l 3 13 l 3 8 l 4 5 l 5 3 l 7 1 l 9 0 l 13 0 l 15 1 l 17 3 l 18 5 l 19 8 l 19 13 l 18 16 l 17 18 l 15 20 l 13 21 l 9 21 ",x_min:3,x_max:19},P:{ha:21,o:"m 4 21 l 4 0 m 4 21 l 13 21 l 16 20 l 17 19 l 18 17 l 18 14 l 17 12 l 16 11 l 13 10 l 4 10 ",
x_min:4,x_max:18},Q:{ha:22,o:"m 9 21 l 7 20 l 5 18 l 4 16 l 3 13 l 3 8 l 4 5 l 5 3 l 7 1 l 9 0 l 13 0 l 15 1 l 17 3 l 18 5 l 19 8 l 19 13 l 18 16 l 17 18 l 15 20 l 13 21 l 9 21 m 12 4 l 18 -2 ",x_min:3,x_max:19},R:{ha:21,o:"m 4 21 l 4 0 m 4 21 l 13 21 l 16 20 l 17 19 l 18 17 l 18 15 l 17 13 l 16 12 l 13 11 l 4 11 m 11 11 l 18 0 ",x_min:4,x_max:18},S:{ha:20,o:"m 17 18 l 15 20 l 12 21 l 8 21 l 5 20 l 3 18 l 3 16 l 4 14 l 5 13 l 7 12 l 13 10 l 15 9 l 16 8 l 17 6 l 17 3 l 15 1 l 12 0 l 8 0 l 5 1 l 3 3 ",
x_min:3,x_max:17},T:{ha:16,o:"m 8 21 l 8 0 m 1 21 l 15 21 ",x_min:1,x_max:15},U:{ha:22,o:"m 4 21 l 4 6 l 5 3 l 7 1 l 10 0 l 12 0 l 15 1 l 17 3 l 18 6 l 18 21 ",x_min:4,x_max:18},V:{ha:18,o:"m 1 21 l 9 0 m 17 21 l 9 0 ",x_min:1,x_max:17},W:{ha:24,o:"m 2 21 l 7 0 m 12 21 l 7 0 m 12 21 l 17 0 m 22 21 l 17 0 ",x_min:2,x_max:22},X:{ha:20,o:"m 3 21 l 17 0 m 17 21 l 3 0 ",x_min:3,x_max:17},Y:{ha:18,o:"m 1 21 l 9 11 l 9 0 m 17 21 l 9 11 ",x_min:1,x_max:17},Z:{ha:20,o:"m 17 21 l 3 0 m 3 21 l 17 21 m 3 0 l 17 0 ",
x_min:3,x_max:17},"[":{ha:14,o:"m 4 25 l 4 -7 m 5 25 l 5 -7 m 4 25 l 11 25 m 4 -7 l 11 -7 ",x_min:4,x_max:11},"\\":{ha:14,o:"m 0 21 l 14 -3 ",x_min:0,x_max:14},"]":{ha:14,o:"m 9 25 l 9 -7 m 10 25 l 10 -7 m 3 25 l 10 25 m 3 -7 l 10 -7 ",x_min:3,x_max:10},"^":{ha:14,o:"m 3 10 l 8 18 l 13 10 ",x_min:3,x_max:13},_:{ha:16,o:"m 0 -2 l 16 -2 ",x_min:0,x_max:16},"`":{ha:10,o:"m 6 21 l 5 20 l 4 18 l 4 16 l 5 15 l 6 16 l 5 17 ",x_min:4,x_max:6},a:{ha:19,o:"m 15 14 l 15 0 m 15 11 l 13 13 l 11 14 l 8 14 l 6 13 l 4 11 l 3 8 l 3 6 l 4 3 l 6 1 l 8 0 l 11 0 l 13 1 l 15 3 ",
x_min:3,x_max:15},b:{ha:19,o:"m 4 21 l 4 0 m 4 11 l 6 13 l 8 14 l 11 14 l 13 13 l 15 11 l 16 8 l 16 6 l 15 3 l 13 1 l 11 0 l 8 0 l 6 1 l 4 3 ",x_min:4,x_max:16},c:{ha:18,o:"m 15 11 l 13 13 l 11 14 l 8 14 l 6 13 l 4 11 l 3 8 l 3 6 l 4 3 l 6 1 l 8 0 l 11 0 l 13 1 l 15 3 ",x_min:3,x_max:15},d:{ha:19,o:"m 15 21 l 15 0 m 15 11 l 13 13 l 11 14 l 8 14 l 6 13 l 4 11 l 3 8 l 3 6 l 4 3 l 6 1 l 8 0 l 11 0 l 13 1 l 15 3 ",x_min:3,x_max:15},e:{ha:18,o:"m 3 8 l 15 8 l 15 10 l 14 12 l 13 13 l 11 14 l 8 14 l 6 13 l 4 11 l 3 8 l 3 6 l 4 3 l 6 1 l 8 0 l 11 0 l 13 1 l 15 3 ",
x_min:3,x_max:15},f:{ha:12,o:"m 10 21 l 8 21 l 6 20 l 5 17 l 5 0 m 2 14 l 9 14 ",x_min:2,x_max:10},g:{ha:19,o:"m 15 14 l 15 -2 l 14 -5 l 13 -6 l 11 -7 l 8 -7 l 6 -6 m 15 11 l 13 13 l 11 14 l 8 14 l 6 13 l 4 11 l 3 8 l 3 6 l 4 3 l 6 1 l 8 0 l 11 0 l 13 1 l 15 3 ",x_min:3,x_max:15},h:{ha:19,o:"m 4 21 l 4 0 m 4 10 l 7 13 l 9 14 l 12 14 l 14 13 l 15 10 l 15 0 ",x_min:4,x_max:15},i:{ha:8,o:"m 3 21 l 4 20 l 5 21 l 4 22 l 3 21 m 4 14 l 4 0 ",x_min:3,x_max:5},j:{ha:10,o:"m 5 21 l 6 20 l 7 21 l 6 22 l 5 21 m 6 14 l 6 -3 l 5 -6 l 3 -7 l 1 -7 ",
x_min:1,x_max:7},k:{ha:17,o:"m 4 21 l 4 0 m 14 14 l 4 4 m 8 8 l 15 0 ",x_min:4,x_max:15},l:{ha:8,o:"m 4 21 l 4 0 ",x_min:4,x_max:4},m:{ha:30,o:"m 4 14 l 4 0 m 4 10 l 7 13 l 9 14 l 12 14 l 14 13 l 15 10 l 15 0 m 15 10 l 18 13 l 20 14 l 23 14 l 25 13 l 26 10 l 26 0 ",x_min:4,x_max:26},n:{ha:19,o:"m 4 14 l 4 0 m 4 10 l 7 13 l 9 14 l 12 14 l 14 13 l 15 10 l 15 0 ",x_min:4,x_max:15},o:{ha:19,o:"m 8 14 l 6 13 l 4 11 l 3 8 l 3 6 l 4 3 l 6 1 l 8 0 l 11 0 l 13 1 l 15 3 l 16 6 l 16 8 l 15 11 l 13 13 l 11 14 l 8 14 ",
x_min:3,x_max:16},p:{ha:19,o:"m 4 14 l 4 -7 m 4 11 l 6 13 l 8 14 l 11 14 l 13 13 l 15 11 l 16 8 l 16 6 l 15 3 l 13 1 l 11 0 l 8 0 l 6 1 l 4 3 ",x_min:4,x_max:16},q:{ha:19,o:"m 15 14 l 15 -7 m 15 11 l 13 13 l 11 14 l 8 14 l 6 13 l 4 11 l 3 8 l 3 6 l 4 3 l 6 1 l 8 0 l 11 0 l 13 1 l 15 3 ",x_min:3,x_max:15},r:{ha:13,o:"m 4 14 l 4 0 m 4 8 l 5 11 l 7 13 l 9 14 l 12 14 ",x_min:4,x_max:12},s:{ha:17,o:"m 14 11 l 13 13 l 10 14 l 7 14 l 4 13 l 3 11 l 4 9 l 6 8 l 11 7 l 13 6 l 14 4 l 14 3 l 13 1 l 10 0 l 7 0 l 4 1 l 3 3 ",
x_min:3,x_max:14},t:{ha:12,o:"m 5 21 l 5 4 l 6 1 l 8 0 l 10 0 m 2 14 l 9 14 ",x_min:2,x_max:10},u:{ha:19,o:"m 4 14 l 4 4 l 5 1 l 7 0 l 10 0 l 12 1 l 15 4 m 15 14 l 15 0 ",x_min:4,x_max:15},v:{ha:16,o:"m 2 14 l 8 0 m 14 14 l 8 0 ",x_min:2,x_max:14},w:{ha:22,o:"m 3 14 l 7 0 m 11 14 l 7 0 m 11 14 l 15 0 m 19 14 l 15 0 ",x_min:3,x_max:19},x:{ha:17,o:"m 3 14 l 14 0 m 14 14 l 3 0 ",x_min:3,x_max:14},y:{ha:16,o:"m 2 14 l 8 0 m 14 14 l 8 0 l 6 -4 l 4 -6 l 2 -7 l 1 -7 ",x_min:1,x_max:14},z:{ha:17,o:"m 14 14 l 3 0 m 3 14 l 14 14 m 3 0 l 14 0 ",
x_min:3,x_max:14},"{":{ha:14,o:"m 9 25 l 7 24 l 6 23 l 5 21 l 5 19 l 6 17 l 7 16 l 8 14 l 8 12 l 6 10 m 7 24 l 6 22 l 6 20 l 7 18 l 8 17 l 9 15 l 9 13 l 8 11 l 4 9 l 8 7 l 9 5 l 9 3 l 8 1 l 7 0 l 6 -2 l 6 -4 l 7 -6 m 6 8 l 8 6 l 8 4 l 7 2 l 6 1 l 5 -1 l 5 -3 l 6 -5 l 7 -6 l 9 -7 ",x_min:4,x_max:9},"|":{ha:8,o:"m 4 25 l 4 -7 ",x_min:4,x_max:4},"}":{ha:14,o:"m 5 25 l 7 24 l 8 23 l 9 21 l 9 19 l 8 17 l 7 16 l 6 14 l 6 12 l 8 10 m 7 24 l 8 22 l 8 20 l 7 18 l 6 17 l 5 15 l 5 13 l 6 11 l 10 9 l 6 7 l 5 5 l 5 3 l 6 1 l 7 0 l 8 -2 l 8 -4 l 7 -6 m 8 8 l 6 6 l 6 4 l 7 2 l 8 1 l 9 -1 l 9 -3 l 8 -5 l 7 -6 l 5 -7 ",
x_min:5,x_max:10},"~":{ha:24,o:"m 3 6 l 3 8 l 4 11 l 6 12 l 8 12 l 10 11 l 14 8 l 16 7 l 18 7 l 20 8 l 21 10 m 3 8 l 4 10 l 6 11 l 8 11 l 10 10 l 14 7 l 16 6 l 18 6 l 20 7 l 21 10 l 21 12 ",x_min:3,x_max:21}},strokeFont:d,cssFontWeight:"normal",ascender:28,descender:-6,cssFontStyle:"normal",boundingBox:{yMin:-7,xMin:0,yMax:25,xMax:26},resolution:24,original_font_information:{postscript_name:"sans-serif",version_string:"1.00",vendor_url:"",full_font_name:"sans-serif",font_family_name:"sans-serif",
copyright:"",description:"",trademark:"",designer:"",designer_url:"",unique_font_identifier:"",license_url:"",license_description:"",manufacturer_name:"",font_sub_family_name:"normal"},familyName:"sans-serif",lineHeight:24});window.jspd=A;A.objects=A.aa;A.graphics=A.ia;A.graphics.rectangle=A.ia.La;
A.objects.external=function(){A.aa.object.call(this);this.label="external";this.ba=[];this.ca=[];this.iam_external=function(a,b){A.pa["jspd.objects."+a]=b;this.label=this.config.label;for(var c=0;c<this.config.inlets;c++)this.ba.push(new A.da(this));for(c=0;c<this.config.outlets;c++)this.ca.push(new A.fa(this));if(this.config.execute!=e)this.execute=this.config.execute;if(this.config.onLoad!=e)this.Ga=this.config.onLoad;this.outlets=this.ca;for(outlet in this.ca)this.ca[outlet].send=this.ca[outlet].send;
this.la=this.box}};var O=document.body,P=document.createElement("div");P.setAttribute("id","jspd");P.setAttribute("style","display:none");var Q=document.createElement("div");Q.setAttribute("id","toolbar");Q.setAttribute("style","padding: 10px 0px; height:30px");var R=document.createElement("div");R.setAttribute("class","logo");var M=document.createTextNode("jspd");R.appendChild(M);Q.appendChild(R);P.appendChild(Q);var S=document.createElement("div");S.setAttribute("id","container");var T=document.createElement("canvas");
T.setAttribute("id","imageView");T.setAttribute("height","500px");T.setAttribute("width","800px");S.appendChild(T);P.appendChild(S);O.appendChild(P);
